---
title: "Personal Site"
author: "Dania Jafar"
date: "10/27/2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")
#create a table showing the 10 most popular items in the baking aisle
instacart2 = instacart %>% 
  select(aisle_id, aisle, product_name) %>% 
  filter(aisle == "baking ingredients") %>% 
count(aisle, product_name) %>% 
group_by(aisle) %>% 
top_n(10) 

instacart2 %>% 
  arrange(n) %>% 
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name , y = ~n  , color = ~product_name, type = "bar") %>%  
  layout(xaxis  = list(title = "Product", showticklabels = FALSE), 
        yaxis = list(title = "Number Ordered"), 
         title = 'The Top 10 Baking Ingredients Ordered') 
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
  instacart %>% 
  filter(product_name %in% c("Organic Hass Avocado", "Strawberries", "Carrots", "Water", "Banana", "Cheese Pizza", "Ice Cream Variety Pack", "	Chunky Peanut Butter")) %>% 
  plot_ly(x = ~product_name, y = ~order_hour_of_day, color = ~product_name, type = "box",
          colors = "Set2") %>% 
layout(xaxis  = list(title = "Product Name", showticklabels = FALSE), 
        yaxis = list(title = "Order Hour of the Day"), 
         title = 'Products by Hour of the Day they are Ordered') 

```

### Chart C

```{r}
instacart %>% 
  filter(aisle %in% c("cookies cakes", "candy chocolate", "spreads", "ice cream ice")) %>%
  mutate(
    aisle = as.factor(aisle)
  ) %>% 
  select(aisle, days_since_prior_order) %>% 
  plot_ly(x = ~aisle,
    y = ~days_since_prior_order,
type = 'violin') %>% 
layout(xaxis  = list(title = "Aisle"), 
        yaxis = list(title = "Days Since Prior Order"), 
         title = 'Aisles by Days Since Prior Order') 

    
```




```


